In [ ]:
#@title Installing required packages

!pip install deepface
!pip install retina-face

Collecting deepface
  Downloading deepface-0.0.90-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 kB 3.7 MB/s eta 0:00:00
Requirement already satisfied: requests>=2.27.1 in /usr/local/lib/python3.10/dist-packages (from deepface) (2.31.0)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from deepface) (1.25.2)
Requirement already satisfied: pandas>=0.23.4 in /usr/local/lib/python3.10/dist-packages (from deepface) (2.0.3)
Requirement already satisfied: gdown>=3.10.1 in /usr/local/lib/python3.10/dist-packages (from deepface) (4.7.3)
Requirement already satisfied: tqdm>=4.30.0 in /usr/local/lib/python3.10/dist-packages (from deepface) (4.66.2)
Requirement already satisfied: Pillow>=5.2.0 in /usr/local/lib/python3.10/dist-packages (from deepface) (9.4.0)
Requirement already satisfied: opencv-python>=4.5.5.64 in /usr/local/lib/python3.10/dist-packages (from deepface) (4.8.0.76)
Requirement already satisfied: tensorflow>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from deepface) (2.15.0)
Requirement already satisfied: keras>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from deepface) (2.15.0)
Requirement already satisfied: Flask>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from deepface) (2.2.5)
Collecting mtcnn>=0.1.0 (from deepface)
  Downloading mtcnn-0.1.1-py3-none-any.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 21.1 MB/s eta 0:00:00
Collecting retina-face>=0.0.1 (from deepface)
  Downloading retina_face-0.0.17-py3-none-any.whl (25 kB)
Collecting fire>=0.4.0 (from deepface)
  Downloading fire-0.6.0.tar.gz (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.4/88.4 kB 12.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting gunicorn>=20.1.0 (from deepface)
  Downloading gunicorn-22.0.0-py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.4/84.4 kB 11.0 MB/s eta 0:00:00
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from fire>=0.4.0->deepface) (1.16.0)
Requirement already satisfied: termcolor in /usr/local/lib/python3.10/dist-packages (from fire>=0.4.0->deepface) (2.4.0)
Requirement already satisfied: Werkzeug>=2.2.2 in /usr/local/lib/python3.10/dist-packages (from Flask>=1.1.2->deepface) (3.0.2)
Requirement already satisfied: Jinja2>=3.0 in /usr/local/lib/python3.10/dist-packages (from Flask>=1.1.2->deepface) (3.1.3)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.10/dist-packages (from Flask>=1.1.2->deepface) (2.1.2)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.10/dist-packages (from Flask>=1.1.2->deepface) (8.1.7)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from gdown>=3.10.1->deepface) (3.13.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from gdown>=3.10.1->deepface) (4.12.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from gunicorn>=20.1.0->deepface) (24.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.23.4->deepface) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.23.4->deepface) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.23.4->deepface) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.27.1->deepface) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.27.1->deepface) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.27.1->deepface) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.27.1->deepface) (2024.2.2)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (0.5.4)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (3.9.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (18.1.1)
Requirement already satisfied: ml-dtypes~=0.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (0.2.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (3.3.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (3.20.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (67.7.2)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (4.11.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (0.36.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (1.62.1)
Requirement already satisfied: tensorboard<2.16,>=2.15 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (2.15.2)
Requirement already satisfied: tensorflow-estimator<2.16,>=2.15.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->deepface) (2.15.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow>=1.9.0->deepface) (0.43.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from Jinja2>=3.0->Flask>=1.1.2->deepface) (2.1.5)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (2.27.0)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (1.2.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (3.6)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (0.7.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->gdown>=3.10.1->deepface) (2.5)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from requests>=2.27.1->deepface) (1.7.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (5.3.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (0.4.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (1.3.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (0.6.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->deepface) (3.2.2)
Building wheels for collected packages: fire
  Building wheel for fire (setup.py) ... done
  Created wheel for fire: filename=fire-0.6.0-py2.py3-none-any.whl size=117029 sha256=7ae68e00b634b1255763a9b30e79b92fed57f51494310284573bd267830f2d09
  Stored in directory: /root/.cache/pip/wheels/d6/6d/5d/5b73fa0f46d01a793713f8859201361e9e581ced8c75e5c6a3
Successfully built fire
Installing collected packages: gunicorn, fire, mtcnn, retina-face, deepface
Successfully installed deepface-0.0.90 fire-0.6.0 gunicorn-22.0.0 mtcnn-0.1.1 retina-face-0.0.17
Requirement already satisfied: retina-face in /usr/local/lib/python3.10/dist-packages (0.0.17)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from retina-face) (1.25.2)
Requirement already satisfied: gdown>=3.10.1 in /usr/local/lib/python3.10/dist-packages (from retina-face) (4.7.3)
Requirement already satisfied: Pillow>=5.2.0 in /usr/local/lib/python3.10/dist-packages (from retina-face) (9.4.0)
Requirement already satisfied: opencv-python>=3.4.4 in /usr/local/lib/python3.10/dist-packages (from retina-face) (4.8.0.76)
Requirement already satisfied: tensorflow>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from retina-face) (2.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from gdown>=3.10.1->retina-face) (3.13.4)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.10/dist-packages (from gdown>=3.10.1->retina-face) (2.31.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from gdown>=3.10.1->retina-face) (1.16.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from gdown>=3.10.1->retina-face) (4.66.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from gdown>=3.10.1->retina-face) (4.12.3)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->retina-face) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->retina-face) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->retina-face) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->retina-face) (0.5.4)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->retina-face) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->retina-face) (3.9.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->retina-face) (18.1.1)
Requirement already satisfied: ml-dtypes~=0.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->retina-face) (0.2.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->retina-face) (3.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->retina-face) (24.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->retina-face) (3.20.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->retina-face) (67.7.2)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->retina-face) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->retina-face) (4.11.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->retina-face) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->retina-face) (0.36.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->retina-face) (1.62.1)
Requirement already satisfied: tensorboard<2.16,>=2.15 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->retina-face) (2.15.2)
Requirement already satisfied: tensorflow-estimator<2.16,>=2.15.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->retina-face) (2.15.0)
Requirement already satisfied: keras<2.16,>=2.15.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=1.9.0->retina-face) (2.15.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow>=1.9.0->retina-face) (0.43.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow>=1.9.0->retina-face) (2.27.0)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow>=1.9.0->retina-face) (1.2.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow>=1.9.0->retina-face) (3.6)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow>=1.9.0->retina-face) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow>=1.9.0->retina-face) (3.0.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->gdown>=3.10.1->retina-face) (2.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown>=3.10.1->retina-face) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown>=3.10.1->retina-face) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown>=3.10.1->retina-face) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown>=3.10.1->retina-face) (2024.2.2)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown>=3.10.1->retina-face) (1.7.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->retina-face) (5.3.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->retina-face) (0.4.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->retina-face) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->retina-face) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->retina-face) (2.1.5)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->retina-face) (0.6.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow>=1.9.0->retina-face) (3.2.2)

In [ ]:
#@title Import Packages

# Data handling
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Image specific
import cv2
from google.colab.patches import cv2_imshow

# RetinaFace
from retinaface import RetinaFace
from retinaface.commons import preprocess, postprocess
# DeepFace
from deepface import DeepFace

import uuid
from tqdm.notebook import tqdm

import os
from os import path
import warnings
import pickle

24-04-18 08:52:44 - Directory /root/.deepface created
24-04-18 08:52:44 - Directory /root/.deepface/weights created

In [ ]:
#@title Load an unzip images for face detection

!unzip -q ../data/posts.zip -d ./images
!unzip -q ../data/2024-01-03-database-final-v4.zip -d ./database_final-v1
!unzip -q ../data/2024-04-17-Faces-Posts-Images.zip -d ./Exports

In [ ]:
!unzip -q ../data/2024-04-17-Faces-Posts-Images.zip

In [ ]:
#@title Import data farmes

all_faces_v2_df = pd.read_csv('../data/2024-03-18-Retina-Face-Posts-Detection.csv')
#images_v2_df = pd.read_csv('../dataimages_v2.csv')
#all_faces_tasks_df = pd.read_csv('../dataAllFaces-Tasks.csv')

In [ ]:
import ast

all_faces_v2_df["facial_area"] = all_faces_v2_df["facial_area"].apply(ast.literal_eval)
all_faces_v2_df["right_eye"] = all_faces_v2_df["right_eye"].apply(ast.literal_eval)
all_faces_v2_df["left_eye"] = all_faces_v2_df["left_eye"].apply(ast.literal_eval)
all_faces_v2_df["nose"] = all_faces_v2_df["nose"].apply(ast.literal_eval)
all_faces_v2_df["mouth_right"] = all_faces_v2_df["mouth_right"].apply(ast.literal_eval)
all_faces_v2_df["mouth_left"] = all_faces_v2_df["mouth_left"].apply(ast.literal_eval)

In [ ]:
all_faces_v2_df['filename'] = all_faces_v2_df['bucket_url'].apply(lambda image: image.replace('../data/', ''))

In [ ]:
all_faces_v2_df['account_name'] = all_faces_v2_df['filename'].apply(lambda x: x.split('/')[0])

In [ ]:
all_faces_v2_df.head()

,image,type,bucket_url,face_uuid,retina_face_score,facial_area,right_eye,left_eye,nose,mouth_right,...,f_pixel_x,f_pixel_y,f_pixel_width,f_pixel_height,f_relativ_x,f_relativ_y,f_relativ_width,f_relativ_height,filename,account_name
0,images/armin_laschet/2021-09-22_14-55-06_UTC_2...,Post,gs://ig-politik-posts/armin_laschet/2021-09-22...,1e19a944-ce54-4a50-af5f-1fb26ae46852,0.999463,"[618, 68, 698, 179]","[655.83215, 115.59756]","[687.78125, 116.61998]","[679.88385, 137.47713]","[651.548, 148.28584]",...,618,68,80,111,42.916667,7.943925,5.555556,12.967290,armin_laschet/2021-09-22_14-55-06_UTC_2.jpg,armin_laschet
1,images/armin_laschet/2021-09-22_14-55-06_UTC_2...,Post,gs://ig-politik-posts/armin_laschet/2021-09-22...,7c50af0d-d49f-4121-921b-173b16eb9a63,0.999458,"[865, 76, 941, 176]","[882.80505, 117.19016]","[918.87573, 113.6915]","[901.9659, 135.02817]","[887.5133, 148.83932]",...,865,76,76,100,60.069444,8.878505,5.277778,11.682243,armin_laschet/2021-09-22_14-55-06_UTC_2.jpg,armin_laschet
2,images/armin_laschet/2021-09-22_14-55-06_UTC_2...,Post,gs://ig-politik-posts/armin_laschet/2021-09-22...,f0902030-6596-4e02-a702-9ac7c47c5e16,0.999433,"[217, 96, 293, 203]","[247.93494, 139.99324]","[282.4035, 137.506]","[276.23734, 155.95622]","[253.7339, 175.65933]",...,217,96,76,107,15.069444,11.214953,5.277778,12.500000,armin_laschet/2021-09-22_14-55-06_UTC_2.jpg,armin_laschet
3,images/armin_laschet/2021-09-22_14-55-06_UTC_2...,Post,gs://ig-politik-posts/armin_laschet/2021-09-22...,d4d4e4e0-f05f-47f5-8dc3-754335fd3e62,0.995322,"[418, 111, 460, 165]","[427.0738, 133.0951]","[445.76318, 133.36816]","[434.90997, 144.35779]","[429.42117, 153.67068]",...,418,111,42,54,29.027778,12.967290,2.916667,6.308411,armin_laschet/2021-09-22_14-55-06_UTC_2.jpg,armin_laschet
4,images/armin_laschet/2021-09-22_14-55-06_UTC_2...,Post,gs://ig-politik-posts/armin_laschet/2021-09-22...,b57bfd65-c875-4f24-9273-ed43955386d2,0.995100,"[986, 65, 1075, 227]","[1001.7438, 125.714874]","[1003.1344, 126.80907]","[987.33704, 157.53435]","[1007.1196, 187.25154]",...,986,65,89,162,68.472222,7.593458,6.180556,18.925234,armin_laschet/2021-09-22_14-55-06_UTC_2.jpg,armin_laschet

## Preparing Faces

In [ ]:
#@title Align-pre detected faces

def extract_faces_adapted(uuid, align = True, resize = False):
  """
  This functions builds upon the extract_faces function from Sefik Serengils RetinaFace
  https://github.com/serengil/retinaface/blob/master/retinaface/RetinaFace.py#L58.

  extract_faces_adapted extracts and aligns (optinal) all faces in one image.

  Parameters:
      filepath (string): exact filepath of the image, where all face should be
                         extracted from

      align (boolean): toggle face alignment (default is True)

  Returns:
      Returns a list of dicts. Each dict has one key, value pair with an id and
      a corresponding extracted face image.
  """

  current_image = all_faces_v2_df.loc[all_faces_v2_df['face_uuid'] == uuid].iloc[0]

  filepath = f"/content/images/{current_image['filename']}"
  image = cv2.imread(filepath)

  facial_area = current_image['facial_area']
  facial_img = image[facial_area[1]: facial_area[3], facial_area[0]: facial_area[2]]

  if align == True:
    right_eye = current_image['right_eye']
    left_eye =  current_image['left_eye']
    nose = current_image['nose']
    facial_img = postprocess.alignment_procedure(facial_img, right_eye, left_eye, nose)

  image_array = facial_img[0]  # Accessing the numpy array part of the tuple

  file_name = f'/content/Exports/{uuid}.jpg'
  return cv2.imwrite(file_name, image_array[:, :, ::1])

In [ ]:
from tqdm.auto import tqdm
tqdm.pandas()

if os.path.exists('/content/Exports') == False:
  os.mkdir('/content/Exports')


all_faces_v2_df['face_uuid'].progress_apply(extract_faces_adapted)

  0%|          | 0/5210 [00:00<?, ?it/s]

0       True
1       True
2       True
3       True
4       True
        ...
5205    True
5206    True
5207    True
5208    True
5209    True
Name: face_uuid, Length: 5210, dtype: bool

In [ ]:
!zip -r ../data/2024-04-17-Faces-Posts-Images.zip Exports

Die letzten 5000 Zeilen der Streamingausgabe wurden abgeschnitten.
  adding: Exports/906412f9-80a3-4baa-bc1b-8c00da40ec11.jpg (deflated 18%)
  adding: Exports/b82017b0-c82c-477a-8ba9-987c8ef375a3.jpg (deflated 1%)
  adding: Exports/23ab169e-bed1-489f-bd1b-487ee97fdb3f.jpg (deflated 15%)
  adding: Exports/07752f44-9c88-4148-a4c1-df4022c2b2bb.jpg (deflated 2%)
  adding: Exports/305181e7-ec56-4ada-80cd-578bbe55b3e8.jpg (deflated 14%)
  adding: Exports/29184bdc-eca9-4712-9f3e-bd14cc2a6653.jpg (deflated 8%)
  adding: Exports/7cf69cd0-7384-479d-9c0e-f89a59092f8e.jpg (deflated 18%)
  adding: Exports/79cbaf06-aeff-4582-8bb4-24ebefba66df.jpg (deflated 4%)
  adding: Exports/5552551c-70ce-493c-9023-aba4e3cf4025.jpg (deflated 0%)
  adding: Exports/a91ff2a2-ccf9-4e79-b570-1c8d5ec8c2dd.jpg (deflated 16%)
  adding: Exports/7de29690-0bb1-4bc7-870d-f91e71082c35.jpg (deflated 8%)
  adding: Exports/9ef26da7-208a-440e-a9d6-d7155fa8da03.jpg (deflated 8%)
  adding: Exports/10c980ba-f5d1-4332-b82b-aed7e65fbcb0.jpg (deflated 15%)
  adding: Exports/07ec59ac-7f37-4a9d-97ec-1aaf1cb95b32.jpg (deflated 13%)
  adding: Exports/52973d37-f21f-4689-971f-db403ffbcf2b.jpg (deflated 11%)
  adding: Exports/c3ac901f-c8a9-474b-aefa-d60b0b5e2f2e.jpg (deflated 2%)
  adding: Exports/d8ec7754-c45e-4548-96f0-caad2675fbcd.jpg (deflated 5%)
  adding: Exports/23f20bd3-5048-4df3-98e4-1dbd552029e2.jpg (deflated 3%)
  adding: Exports/baaf04c0-a2c7-453b-a24b-2a2779f280cc.jpg (deflated 16%)
  adding: Exports/3b514df1-9e7c-4ace-bce0-de58f03ae160.jpg (deflated 5%)
  adding: Exports/30383295-5c75-4d1f-a49f-1fd9de3aad35.jpg (deflated 13%)
  adding: Exports/103162e1-a532-4f23-bcde-e419338b06d2.jpg (deflated 3%)
  adding: Exports/75e5bb13-ef34-4948-9b0c-6e2835fffb74.jpg (deflated 25%)
  adding: Exports/03b03364-2199-41d4-9d70-3bc0351c400e.jpg (deflated 3%)
  adding: Exports/b29c6813-1c53-43bd-9073-c7465b51487d.jpg (deflated 10%)
  adding: Exports/b7519645-3178-4be3-8c6e-f18b5372ef06.jpg (deflated 18%)
  adding: Exports/60506bff-318f-4c4a-88aa-d2961cd95c38.jpg (deflated 9%)
  adding: Exports/fd62a2a2-72b3-4a2f-810a-a676dc2b0ee5.jpg (deflated 1%)
  adding: Exports/762e7aee-f898-46b7-af7b-54aa9148ce4b.jpg (deflated 3%)
  adding: Exports/aec6ac00-e7cd-41f5-b82c-76d014439189.jpg (deflated 8%)
  adding: Exports/11f14196-e968-4fed-b3fa-25258c5865fa.jpg (deflated 4%)
  adding: Exports/be70d66b-518f-4dd8-b767-63ca0845496d.jpg (deflated 18%)
  adding: Exports/20ee44a9-5503-4a49-b81a-c5242c93dfe4.jpg (deflated 16%)
  adding: Exports/2403ac23-7df7-47d4-a223-c8c999e4b600.jpg (deflated 6%)
  adding: Exports/2c586aec-3775-4d03-a6cb-e0b622391115.jpg (deflated 1%)
  adding: Exports/ca5be9cb-08b1-47ee-a06a-14a029f44741.jpg (deflated 8%)
  adding: Exports/86b5d29d-14be-4a66-a7be-0ffdc84cdc6e.jpg (deflated 15%)
  adding: Exports/cb110fbf-b4aa-469c-a943-862dfab34721.jpg (deflated 3%)
  adding: Exports/63fa359e-cb77-48cc-9416-a381bf1a417a.jpg (deflated 22%)
  adding: Exports/ff9ac377-c042-42b8-8ac8-4a2b11c6e57a.jpg (deflated 4%)
  adding: Exports/1bedadf4-e574-4899-b14e-2f4d08d330c4.jpg (deflated 11%)
  adding: Exports/5137c64a-788b-42ce-93fb-2394f1fddc96.jpg (deflated 6%)
  adding: Exports/e5d72f19-f4ec-4db4-9657-f8968684d1ec.jpg (deflated 5%)
  adding: Exports/7ae071b2-96df-439d-819c-71b5e0cd36b0.jpg (deflated 2%)
  adding: Exports/7f62c9ed-053b-42d4-af98-2453dfb3d9c1.jpg (deflated 3%)
  adding: Exports/9873ef32-b902-451a-a3c2-a431790cd7e3.jpg (deflated 1%)
  adding: Exports/79fc3470-a614-405d-b996-b337a99d4436.jpg (deflated 3%)
  adding: Exports/52735d0a-9f56-4709-8e89-e7231baed287.jpg (deflated 2%)
  adding: Exports/e513e1be-e8e3-480b-a77a-7ea0ca88cde6.jpg (deflated 6%)
  adding: Exports/8989bbd4-25b7-4562-97a9-996e2f6b7d7f.jpg (deflated 1%)
  adding: Exports/3fcd0064-6c32-4545-86ba-e5e8901c2f97.jpg (deflated 3%)
  adding: Exports/61426a65-1696-4a7e-a49d-969e54f8a2f9.jpg (deflated 21%)
  adding: Exports/0ad93ca2-5484-45c0-ae2d-46078f7f6f9c.jpg (deflated 27%)
  adding: Exports/e789d869-f73c-4e3f-8ace-b65c36647c56.jpg (deflated 6%)
  adding: Exports/8ad1e7db-fe74-4237-9506-3bc181c616bd.jpg (deflated 11%)
  adding: Exports/24a0b608-506e-4e11-b44d-b1a0739fcf22.jpg (deflated 6%)
  adding: Exports/bf0d644f-f96e-4751-9cc9-461d93defd92.jpg (deflated 5%)
  adding: Exports/b9b1b488-3c38-43a3-aefb-7f3ab1c2a425.jpg (deflated 4%)
  adding: Exports/96608a09-b46a-4036-a0f3-2757a08be3cd.jpg (deflated 10%)
  adding: Exports/5b6b438b-0683-4b0f-92b0-316e39f9d777.jpg (deflated 2%)
  adding: Exports/1dc72d1a-0525-4c9d-bcc5-44166da69df6.jpg (deflated 10%)
  adding: Exports/295a3251-b807-424b-87c5-1b4f59ae17e6.jpg (deflated 11%)
  adding: Exports/21f99e87-d09e-4d2e-b4e6-23d8dc6d1291.jpg (deflated 1%)
  adding: Exports/a13fc3fb-80a7-434c-8673-9febbe3f2204.jpg (deflated 13%)
  adding: Exports/12117b12-a1d4-42a7-a4da-a5813f08d3fc.jpg (deflated 15%)
  adding: Exports/fbe289d3-4f5f-4dd0-8b34-9c0e42cbbe41.jpg (deflated 5%)
  adding: Exports/bf488c05-84b8-4ea8-881b-c9a28829e02a.jpg (deflated 21%)
  adding: Exports/d89b1663-1c34-494d-ac7d-8d6c84defd59.jpg (deflated 3%)
  adding: Exports/e4643a50-5c48-4ee1-acb7-73b64d191c0c.jpg (deflated 2%)
  adding: Exports/e56c1f02-1037-4060-a30b-f6bfac00ee76.jpg (deflated 1%)
  adding: Exports/07b06b7e-aff5-4e77-9746-63f635cf43d8.jpg (deflated 14%)
  adding: Exports/108fa9d2-c1e9-4f5b-afcc-2de3eb725b0b.jpg (deflated 12%)
  adding: Exports/d7c24fd7-a583-4f40-9e6b-194339a37fa2.jpg (deflated 8%)
  adding: Exports/8bf451b1-478b-4026-8b65-5071d93916d3.jpg (deflated 4%)
  adding: Exports/88ccb0e5-7d8f-47a1-8e64-4f2c2e172f76.jpg (deflated 10%)
  adding: Exports/4b3f36a7-4565-4e7c-8e01-57331265c134.jpg (deflated 0%)
  adding: Exports/dbd0c6f6-13e6-40ef-9a95-c083bbdb6b5c.jpg (deflated 3%)
  adding: Exports/e2b5a349-6e3b-4513-9710-d53912b663e5.jpg (deflated 15%)
  adding: Exports/e128fd70-6ec6-4de1-87e6-6f7e8770ba2c.jpg (deflated 2%)
  adding: Exports/1ec4a184-b79f-4e92-b659-8dd1a8a48e0f.jpg (deflated 1%)
  adding: Exports/d6362fd5-150a-4fc6-8597-0f0a52155a89.jpg (deflated 5%)
  adding: Exports/c895c98c-362d-4b7f-a561-9f04c3c4d4d8.jpg (deflated 2%)
  adding: Exports/5b3c951e-6012-44da-abe6-41e3aa665019.jpg (deflated 22%)
  adding: Exports/4406eeb7-d8ed-4c59-8c8f-160fbec1c0c3.jpg (deflated 0%)
  adding: Exports/26991d97-aa7d-46ee-a84c-8ad237dba537.jpg (deflated 8%)
  adding: Exports/7463bb71-a888-45ff-8c64-340fd4ef195b.jpg (deflated 21%)
  adding: Exports/a002b5ad-a827-4c7f-9399-49ffe00535f8.jpg (deflated 20%)
  adding: Exports/5cf63fae-619b-49f7-9795-7a7b8c9de315.jpg (deflated 7%)
  adding: Exports/0e5dc452-b618-47a8-9dec-d332b9eaaea4.jpg (deflated 9%)
  adding: Exports/a5e10b05-f259-470a-8ffd-15f76778d8c6.jpg (deflated 1%)
  adding: Exports/28842f57-0b72-43ca-aff1-6c72a6044666.jpg (deflated 12%)
  adding: Exports/d8a07b95-a58e-460f-a0ec-ea22475d2ccc.jpg (deflated 4%)
  adding: Exports/b752d073-bc61-4934-a62d-44b28558a861.jpg (deflated 4%)
  adding: Exports/8de355f2-4b25-4973-a3f7-7d2268e7cb7a.jpg (deflated 10%)
  adding: Exports/f86246b3-971a-4d66-9291-aae5181880cf.jpg (deflated 4%)
  adding: Exports/ea6d946c-2f53-40e1-be29-324e065e3e09.jpg (deflated 3%)
  adding: Exports/3ba886fa-3a9f-4455-9af6-dcc90cad0c3e.jpg (deflated 2%)
  adding: Exports/9be85ab6-891e-4e56-bdde-6a2e5a882be6.jpg (deflated 4%)
  adding: Exports/d96378b2-8699-47a1-8973-ffb36f24089a.jpg (deflated 8%)
  adding: Exports/ee3a4872-68e0-489b-ab2f-48b7afdb1f72.jpg (deflated 2%)
  adding: Exports/5733a1ac-63e9-461c-9d5a-83935f8198c5.jpg (deflated 1%)
  adding: Exports/ca40cba1-59e2-4bff-841b-d7603592ba47.jpg (deflated 4%)
  adding: Exports/75306c2e-630e-41db-a499-ae1d2ba13f37.jpg (deflated 2%)
  adding: Exports/a684bc9d-05df-408d-8395-dd3ec4572e3f.jpg (deflated 1%)
  adding: Exports/468bb33a-0687-488a-8344-d0e744135c08.jpg (deflated 3%)
  adding: Exports/adff1b16-2b52-4649-99a4-2df22c08d162.jpg (deflated 8%)
  adding: Exports/e43a2350-d41a-4281-b593-afb21363ac94.jpg (deflated 15%)
  adding: Exports/f76ff9c4-d702-4e87-bab3-ec740bf65eae.jpg (deflated 8%)
  adding: Exports/5bbe81d7-f7a4-46c7-9e65-63de9fd406d2.jpg (deflated 27%)
  adding: Exports/bceb6e8a-30b7-4917-9a98-27327995fe66.jpg (deflated 14%)
  adding: Exports/87e5dd2b-cc62-4ef7-9fd8-594d1fc6bc65.jpg (deflated 12%)
  adding: Exports/00d4cbee-1038-4a1d-93ea-aeb402870566.jpg (deflated 11%)
  adding: Exports/bbfed57c-817a-4d5d-9b9e-5cb08c34de06.jpg (deflated 21%)
  adding: Exports/b8f6b66d-1cbc-4072-ab77-120f31f3158a.jpg (deflated 2%)
  adding: Exports/ab8abd28-e963-48a2-9523-469570ae3d1a.jpg (deflated 26%)
  adding: Exports/04d48bdd-4db7-42d0-b907-218fe6bec266.jpg (deflated 10%)
  adding: Exports/0511c557-3d11-4771-b0ef-a4a5452b2057.jpg (deflated 7%)
  adding: Exports/71b2c2a8-c9eb-48ba-a37c-e13209907e7f.jpg (deflated 7%)
  adding: Exports/eebc888b-5657-4cfa-a5e5-bda69ef71fac.jpg (deflated 10%)
  adding: Exports/793a2802-3db7-4716-a9bd-76ea33900a3b.jpg (deflated 13%)
  adding: Exports/53288108-5afc-4996-a468-d88c148aa0d2.jpg (deflated 3%)
  adding: Exports/209b6853-711f-4446-9802-ebafad1b1eb1.jpg (deflated 23%)
  adding: Exports/65245c39-45e6-4cd1-a1f5-d6efbcc4058d.jpg (deflated 3%)
  adding: Exports/f5341a51-5162-4d83-a535-64291e08e3a8.jpg (deflated 3%)
  adding: Exports/e47047a3-f445-4052-9f29-934abd6c8f7f.jpg (deflated 12%)
  adding: Exports/f5f2a480-1e54-4842-b7d7-95dcf2898669.jpg (deflated 25%)
  adding: Exports/3de1f57b-69a1-488a-b989-0adbb602f8ad.jpg (deflated 3%)
  adding: Exports/526c2645-173f-4924-bc39-58af9063518b.jpg (deflated 5%)
  adding: Exports/7c3d974d-2435-4300-b91b-b69344a2fc6d.jpg (deflated 9%)
  adding: Exports/ef58cfb9-c14d-49cf-aafa-99ec8d2c0b87.jpg (deflated 5%)
  adding: Exports/66f19a7d-b8ae-45ed-9f38-432e3c14adfa.jpg (deflated 1%)
  adding: Exports/005bf45a-fffb-4c21-b4e6-316cf22212cd.jpg (deflated 4%)
  adding: Exports/688aa1b0-d919-4fa4-9562-d8d8dd2a7bed.jpg (deflated 18%)
  adding: Exports/34cbdd3a-85ae-428d-8ceb-a2be90a37dd7.jpg (deflated 1%)
  adding: Exports/2678998d-6e3e-4c23-9c77-f5f55c2d58ad.jpg (deflated 8%)
  adding: Exports/3c497d57-74fe-4ba2-b028-c6019099b2e1.jpg (deflated 4%)
  adding: Exports/e6cd2ae6-47eb-4fdd-8e16-862550f3d18c.jpg (deflated 8%)
  adding: Exports/587f6d26-a72d-48f4-9738-d1635831f759.jpg (deflated 9%)
  adding: Exports/391f1e3c-23b9-4ead-878c-8278a887c425.jpg (deflated 10%)
  adding: Exports/766897b9-85c4-4068-970d-75f95799966c.jpg (deflated 2%)
  adding: Exports/e294b8eb-fd41-47a8-9d91-4bf61215a544.jpg (deflated 15%)
  adding: Exports/b32a6596-c03f-41f2-9c51-21c8b1aaa776.jpg (deflated 1%)
  adding: Exports/096f99ed-cad6-4adf-8058-d55f283603ca.jpg (deflated 13%)
  adding: Exports/4eab5752-1bee-4d3c-bc6f-6c272fa87af9.jpg (deflated 2%)
  adding: Exports/081b4119-55a6-40e5-8279-f783f08a32da.jpg (deflated 16%)
  adding: Exports/97de8175-00d0-4a9b-a203-afedc9d829b5.jpg (deflated 2%)
  adding: Exports/9eb3f5a7-0149-43db-8e6b-c4024ae960bd.jpg (deflated 1%)
  adding: Exports/ff9243d9-22d9-4b27-9cae-61dcb5cc54a5.jpg (deflated 3%)
  adding: Exports/80d105e9-496a-4647-9b46-23f8dbdbe391.jpg (deflated 5%)
  adding: Exports/cabe0f89-c99d-4e54-a95a-f9b5ecf97ec5.jpg (deflated 10%)
  adding: Exports/64aa8135-31b2-47d4-91b3-732859a95f6f.jpg (deflated 3%)
  adding: Exports/4f8ee405-4696-4451-8660-d6ff84496cbc.jpg (deflated 6%)
  adding: Exports/45fba16d-ff36-44a6-a9dd-2ad984614926.jpg (deflated 10%)
  adding: Exports/59d54d21-300a-428a-94ae-6c07589155db.jpg (deflated 19%)
  adding: Exports/5e18c99b-8c80-4d40-9181-1ae6b61e69a9.jpg (deflated 3%)
  adding: Exports/16f387d4-a825-40ea-9a02-2f1ed07c5dbb.jpg (deflated 10%)
  adding: Exports/e3b45e7c-48fc-48f4-9d74-d2b11bf3a10f.jpg (deflated 1%)
  adding: Exports/e8369aed-83b5-4b38-ad34-cd18b8f7334c.jpg (deflated 2%)
  adding: Exports/1cdc8da3-86aa-48f8-bff2-d32656dd9bae.jpg (deflated 8%)
  adding: Exports/03dca386-b5b6-4f0f-bfd3-20decfbeb92f.jpg (deflated 15%)
  adding: Exports/5e983f8e-951b-473a-ae3e-43f4bd2164d9.jpg (deflated 10%)
  adding: Exports/278b49eb-0717-4b3c-8373-ef977019fade.jpg (deflated 9%)
  adding: Exports/1bb27f73-92ba-4e51-9321-cbcbb87bbf50.jpg (deflated 1%)
  adding: Exports/e6809b07-9b1f-4e12-a499-9b8e8c4464e6.jpg (deflated 1%)
  adding: Exports/a02cb925-0244-4c00-9627-6058512d9c9b.jpg (deflated 1%)
  adding: Exports/8c589de3-9d84-4566-9a70-cacde1f55f4b.jpg (deflated 3%)
  adding: Exports/b1b4dff5-ab96-479e-a7f3-90a5d0fbf3d6.jpg (deflated 10%)
  adding: Exports/4ee44fbf-586d-4a82-a4ad-1bf3ff50d112.jpg (deflated 4%)
  adding: Exports/12650b3e-73b4-4044-b6b6-0e2cd1c60e96.jpg (deflated 23%)
  adding: Exports/6ffffd48-9d3f-4876-bb80-2060982593d4.jpg (deflated 2%)
  adding: Exports/1fd45263-aaf5-4f5c-b5ab-7379018dbfc3.jpg (deflated 7%)
  adding: Exports/46e088fd-e591-45fa-baa1-cf1131456d0d.jpg (deflated 10%)
  adding: Exports/5d7cb5bf-2474-4a4f-ae70-12ade3840a35.jpg (deflated 27%)
  adding: Exports/12200699-8085-4bf4-a6cb-393f4f085ba0.jpg (deflated 2%)
  adding: Exports/e6e6a1da-ef49-44bc-a01c-5d7d713e8795.jpg (deflated 10%)
  adding: Exports/8c1c7300-d5b3-419e-a2b4-09f0977f4de0.jpg (deflated 16%)
  adding: Exports/d67ca254-de7b-4287-b934-fae217d5e784.jpg (deflated 7%)
  adding: Exports/d3112bef-fb20-4d11-8012-65da3bdb7a01.jpg (deflated 1%)
  adding: Exports/48a801d5-0b2b-4596-bf2e-339700c7503d.jpg (deflated 11%)
  adding: Exports/7962baac-3160-4e31-a75c-dec7875d5d23.jpg (deflated 2%)
  adding: Exports/a8c2ba08-5d05-4b0f-96de-a7a589313da3.jpg (deflated 1%)
  adding: Exports/6fe3e39e-d19f-4e08-bdc4-a127751447e2.jpg (deflated 4%)
  adding: Exports/44d6a43d-875a-4eef-aeb3-3106f72b8db9.jpg (deflated 5%)
  adding: Exports/aeae1aca-c8e1-4ec0-aff0-d1202f4f0b36.jpg (deflated 2%)
  adding: Exports/60a55591-ea52-4881-95b4-0f8779d9f3a9.jpg (deflated 2%)
  adding: Exports/fd4f9733-51ea-4a16-a1e3-ef9d089f39c8.jpg (deflated 7%)
  adding: Exports/9d287271-dc9c-47a3-9118-f7f0590110fb.jpg (deflated 17%)
  adding: Exports/85433710-f064-40ac-821c-ed0c3afb8c4c.jpg (deflated 1%)
  adding: Exports/7e2d3e5c-ae55-4d33-87f5-efbaab5d9867.jpg (deflated 9%)
  adding: Exports/f90cd790-c932-4ea6-8997-2fb184c42fa8.jpg (deflated 25%)
  adding: Exports/3c5c52d4-7cc9-4b10-ac77-dbefdc7bfb71.jpg (deflated 3%)
  adding: Exports/83ee328d-3c2d-4a2e-bdf1-bbcdfecc9293.jpg (deflated 22%)
  adding: Exports/f5e81ff4-9ff1-4cf4-9b71-b3813a0878e7.jpg (deflated 12%)
  adding: Exports/f8e0e3d8-a489-4dca-b83a-edc607247a21.jpg (deflated 6%)
  adding: Exports/802499f4-3744-4315-98c8-3de197dfb536.jpg (deflated 10%)
  adding: Exports/6dd15658-d53c-470d-9d8f-0d4781c27d80.jpg (deflated 7%)
  adding: Exports/a6eff40c-982b-41ec-b85b-6172feb12ef1.jpg (deflated 25%)
  adding: Exports/ef448582-3da6-4e9e-94ab-5065cb145772.jpg (deflated 18%)
  adding: Exports/7798b72d-0b57-40cd-b4bf-d78337184e28.jpg (deflated 4%)
  adding: Exports/cfa62c7d-8cce-4899-bbce-471b08b5c548.jpg (deflated 8%)
  adding: Exports/135e0dc1-f6c2-4f1a-ba4a-de80f9935112.jpg (deflated 17%)
  adding: Exports/44696d81-4dcd-4198-ba7a-bf58695f5e84.jpg (deflated 1%)
  adding: Exports/fd09b2e7-9f86-4a8b-9533-84b7073fe4c0.jpg (deflated 24%)
  adding: Exports/fb84e5f5-08a5-4b56-9bcc-11a57dd7a55e.jpg (deflated 7%)
  adding: Exports/d2a447eb-33ea-4fdf-9459-5c7c9bc58eeb.jpg (deflated 3%)
  adding: Exports/140582a1-a5c5-4768-a676-4d010045eaaf.jpg (deflated 7%)
  adding: Exports/a2577d41-6203-463e-8ca5-96bf61c0dd2b.jpg (deflated 7%)
  adding: Exports/f6ce7e0e-2032-431b-ab8d-8b23f69f4ab8.jpg (deflated 22%)
  adding: Exports/052cb75e-6108-4f86-a02e-b02b365b42a9.jpg (deflated 3%)
  adding: Exports/8fadbd5d-aaec-4f83-8036-6b51aa8d9a4e.jpg (deflated 4%)
  adding: Exports/21a87f0e-781b-4861-b713-8a6b272e3a81.jpg (deflated 20%)
  adding: Exports/a2481367-bb4b-41ee-a90e-c4e9e1b0d164.jpg (deflated 1%)
  adding: Exports/1c866294-1f00-4f28-98ca-694d79c8b1d4.jpg (deflated 2%)
  adding: Exports/6aa6808a-08ad-483b-b3b0-ea114cfc8113.jpg (deflated 2%)
  adding: Exports/44c69d65-e748-40cc-a5f6-5236ad14f874.jpg (deflated 15%)
  adding: Exports/48bba826-dad8-40aa-abcb-24bf4b1ac485.jpg (deflated 3%)
  adding: Exports/211a82fa-9099-4613-b37d-18fd4477530b.jpg (deflated 4%)
  adding: Exports/de675006-80c0-41b8-8cdb-319269dce384.jpg (deflated 4%)
  adding: Exports/f46fd7fd-6f8c-4cc1-af67-30977daffd08.jpg (deflated 8%)
  adding: Exports/c69ba0e8-8721-4a1a-a691-5ec7aecce563.jpg (deflated 8%)
  adding: Exports/6ae8caa3-882d-4e46-8672-f74f146d1e83.jpg (deflated 2%)
  adding: Exports/0e70bbab-3eb7-4bdd-965d-54b242122515.jpg (deflated 1%)
  adding: Exports/206333b8-087d-49a2-ad4e-e8c3186b6836.jpg (deflated 5%)
  adding: Exports/2ec47e53-71f6-49bc-b52d-ab2ea32ff430.jpg (deflated 1%)
  adding: Exports/30919129-4cfc-4037-a7a6-c58cb5004471.jpg (deflated 7%)
  adding: Exports/4fb3852a-c386-4c23-bec6-e4e1cb192038.jpg (deflated 2%)
  adding: Exports/7d7a255b-db79-492b-9dfa-1acdd3c0f7a1.jpg (deflated 11%)
  adding: Exports/13b84bf5-0d29-41ae-87f7-45858a7c53b1.jpg (deflated 11%)
  adding: Exports/b5a51f9f-a110-4be4-adcd-93dfcffd8058.jpg (deflated 1%)
  adding: Exports/7b6300da-751e-4247-87a8-be45f4d5b269.jpg (deflated 9%)
  adding: Exports/1e8a17db-5e97-4bff-b492-620ddb0838af.jpg (deflated 2%)
  adding: Exports/b6b8abfd-c385-4a98-b87e-a2497df722c7.jpg (deflated 1%)
  adding: Exports/0d7fa263-7ba0-4b98-8d15-37ddc7dc6231.jpg (deflated 1%)
  adding: Exports/f0c29c2b-35c2-4331-87f7-0afda099f964.jpg (deflated 24%)
  adding: Exports/04120f86-1eae-491f-9f66-2caaaae80971.jpg (deflated 11%)
  adding: Exports/b0548d47-e6bf-49a0-b3d9-bb7f2eb5eb18.jpg (deflated 10%)
  adding: Exports/37959267-94e6-42dd-91f3-d15d8d499dd0.jpg (deflated 2%)
  adding: Exports/fef497e3-a78f-45dc-a73b-8dbeefff1076.jpg (deflated 5%)
  adding: Exports/27ad139a-9e1b-429c-851b-672a10d0488c.jpg (deflated 15%)
  adding: Exports/495782bf-7721-4433-9a8a-18fa55e7e265.jpg (deflated 22%)
  adding: Exports/432fd668-98e2-405d-9faf-a08f0e283166.jpg (deflated 3%)
  adding: Exports/35748afe-a093-42f2-a3f5-c5a74b51a0dd.jpg (deflated 3%)
  adding: Exports/32111d33-fa29-44b2-a2ff-16061002691f.jpg (deflated 23%)
  adding: Exports/534c5b34-4ef1-4563-a52a-3030ece11bb6.jpg (deflated 15%)
  adding: Exports/8c9bc4b5-690f-4555-8d17-48c646582373.jpg (deflated 16%)
  adding: Exports/98d19335-db20-4651-9213-f380547e020c.jpg (deflated 11%)
  adding: Exports/1a9d2f2e-eb09-4026-a70e-2ceeae7640f2.jpg (deflated 8%)
  adding: Exports/672884ee-4951-4852-aa30-7977e210feb3.jpg (deflated 9%)
  adding: Exports/c35ac537-8cd3-41ae-ad12-86668cef6601.jpg (deflated 17%)
  adding: Exports/e7111559-3523-4ff6-8f98-8bd2a5177846.jpg (deflated 3%)
  adding: Exports/c5eeb194-d055-4311-8251-2cce9daccc05.jpg (deflated 10%)
  adding: Exports/a4863739-c0cd-48e3-b46f-3ad967a0c058.jpg (deflated 1%)
  adding: Exports/6518c96a-eda8-4fe2-bbdf-de9d9b11aa62.jpg (deflated 7%)
  adding: Exports/88c22877-d1d7-454e-b84c-fcbb2647a20d.jpg (deflated 1%)
  adding: Exports/20c72199-c73b-4019-a026-c81698d20bf4.jpg (deflated 27%)
  adding: Exports/f3210af6-8472-4e6b-8fbf-e4f47155f453.jpg (deflated 3%)
  adding: Exports/648871e4-3647-437b-82a1-d81799450df3.jpg (deflated 5%)
  adding: Exports/e208c435-e4da-4f3a-ab51-9151535be392.jpg (deflated 7%)
  adding: Exports/68fc3fb8-2453-481c-8065-d0602f49fa48.jpg (deflated 2%)
  adding: Exports/8a362552-1dfd-4978-bdcf-889e665c7427.jpg (deflated 1%)
  adding: Exports/3107a752-7c77-4dda-9950-6f49c3589a2f.jpg (deflated 3%)
  adding: Exports/05a823f7-4323-4a16-b04b-eb15fb581c94.jpg (deflated 1%)
  adding: Exports/e6a0da3c-82d1-46be-8a9d-993eeee95115.jpg (deflated 3%)
  adding: Exports/0213a4d0-1d4a-4448-a702-f18bcd2d0b98.jpg (deflated 17%)
  adding: Exports/dadd3cef-0c4d-4381-8c4d-e3f48b13ec30.jpg (deflated 8%)
  adding: Exports/54fdfdf9-9767-4215-a9f6-590765ca556a.jpg (deflated 20%)
  adding: Exports/8c3cb76d-aad4-4de9-8a63-bb14a7fd4f3f.jpg (deflated 5%)
  adding: Exports/5d66fc0f-8b02-4937-a377-c68caacae0ea.jpg (deflated 14%)
  adding: Exports/d2d214d4-22fd-4c2c-93b5-86a7f3c5a23f.jpg (deflated 15%)
  adding: Exports/78d03aa7-1404-4678-9a9c-a4419149402c.jpg (deflated 12%)
  adding: Exports/698bcd26-c6b9-45df-98ac-390df2837130.jpg (deflated 3%)

## Preparing Face Database
Hier habe ich mich nun auf die Kanzlerkandidaten konzentriert.

QuickFix um mit Umlauten gut klar zu kommen.

In [ ]:
import os
import unicodedata

DATABASE = "/content/database_final-v1/2024-01-03-database-final-v4"


def replace_characters(original):
    normalized = unicodedata.normalize('NFC', original)
    # Replace specific characters in the string
    return normalized.replace('ä', 'ae').replace('ö', 'oe').replace('ü', 'ue')

def rename_files_and_folders(path):
    for root, dirs, files in os.walk(path, topdown=False):
        # Rename files
        for name in files:
            new_name = replace_characters(name)
            if new_name != name:
                os.rename(os.path.join(root, name), os.path.join(root, new_name))

        # Rename directories
        for name in dirs:
            new_name = replace_characters(name)
            if new_name != name:
                os.rename(os.path.join(root, name), os.path.join(root, new_name))

rename_files_and_folders(DATABASE)

Filtere nach den Accounts, die mich interessieren

In [ ]:
# Filtere für Kanzlerkandidaten
selected_accounts = ['armin_laschet', 'abaerbock', 'christlichsozialeunion',
       'christianlindner', 'cdu', 'fdp', 'die_gruenen', 'markus.soeder',
       'spdde', 'olafscholz']

all_faces_v2_df = all_faces_v2_df[all_faces_v2_df['account_name'].isin(selected_accounts)]

In [ ]:
all_faces_v2_df.head()

,image,type,bucket_url,face_uuid,retina_face_score,facial_area,right_eye,left_eye,nose,mouth_right,...,f_pixel_y,f_pixel_width,f_pixel_height,f_relativ_x,f_relativ_y,f_relativ_width,f_relativ_height,filename,account_name,Party
0,images/armin_laschet/2021-09-22_14-55-06_UTC_2...,Post,gs://ig-politik-posts/armin_laschet/2021-09-22...,1e19a944-ce54-4a50-af5f-1fb26ae46852,0.999463,"[618, 68, 698, 179]","[655.83215, 115.59756]","[687.78125, 116.61998]","[679.88385, 137.47713]","[651.548, 148.28584]",...,68,80,111,42.916667,7.943925,5.555556,12.967290,armin_laschet/2021-09-22_14-55-06_UTC_2.jpg,armin_laschet,CDU
1,images/armin_laschet/2021-09-22_14-55-06_UTC_2...,Post,gs://ig-politik-posts/armin_laschet/2021-09-22...,7c50af0d-d49f-4121-921b-173b16eb9a63,0.999458,"[865, 76, 941, 176]","[882.80505, 117.19016]","[918.87573, 113.6915]","[901.9659, 135.02817]","[887.5133, 148.83932]",...,76,76,100,60.069444,8.878505,5.277778,11.682243,armin_laschet/2021-09-22_14-55-06_UTC_2.jpg,armin_laschet,CDU
2,images/armin_laschet/2021-09-22_14-55-06_UTC_2...,Post,gs://ig-politik-posts/armin_laschet/2021-09-22...,f0902030-6596-4e02-a702-9ac7c47c5e16,0.999433,"[217, 96, 293, 203]","[247.93494, 139.99324]","[282.4035, 137.506]","[276.23734, 155.95622]","[253.7339, 175.65933]",...,96,76,107,15.069444,11.214953,5.277778,12.500000,armin_laschet/2021-09-22_14-55-06_UTC_2.jpg,armin_laschet,CDU
3,images/armin_laschet/2021-09-22_14-55-06_UTC_2...,Post,gs://ig-politik-posts/armin_laschet/2021-09-22...,d4d4e4e0-f05f-47f5-8dc3-754335fd3e62,0.995322,"[418, 111, 460, 165]","[427.0738, 133.0951]","[445.76318, 133.36816]","[434.90997, 144.35779]","[429.42117, 153.67068]",...,111,42,54,29.027778,12.967290,2.916667,6.308411,armin_laschet/2021-09-22_14-55-06_UTC_2.jpg,armin_laschet,CDU
4,images/armin_laschet/2021-09-22_14-55-06_UTC_2...,Post,gs://ig-politik-posts/armin_laschet/2021-09-22...,b57bfd65-c875-4f24-9273-ed43955386d2,0.995100,"[986, 65, 1075, 227]","[1001.7438, 125.714874]","[1003.1344, 126.80907]","[987.33704, 157.53435]","[1007.1196, 187.25154]",...,65,89,162,68.472222,7.593458,6.180556,18.925234,armin_laschet/2021-09-22_14-55-06_UTC_2.jpg,armin_laschet,CDU

Mapping Account <-> Partei

In [ ]:
party_dict = {
  "armin_laschet": "CDU",
  "spdde": "SPD",
  "afd.bund": "AfD",
  "nicola_beer": "FDP",
  "christianlindner": "FDP",
  "abaerbock": "GRUEN",
  "cdu": "CDU",
  "robert.habeck":  "GRUEN",
  "olafscholz": "SPD",
  "fw_bayern": "FW",
  "die_gruenen":  "GRUEN",
  "christlichsozialeunion":  "CSU",
  "fdp": "FDP",
  "saskiaesken":  "SPD",
  "susanne_hennig_wellsow": "Linke",
  "atesgurpinar":  "Linke",
  "grey_gor": "FW",
  "markus.soeder":  "CSU",
  "dielinke":  "Linke",
  "joerg.meuthen": "AfD",
  "engin_eroglu_": "FW",
}
all_faces_v2_df['Party'] = all_faces_v2_df['account_name'].map(party_dict)

In [ ]:
all_faces_v2_df.head()

,image,type,bucket_url,face_uuid,retina_face_score,facial_area,right_eye,left_eye,nose,mouth_right,...,f_pixel_y,f_pixel_width,f_pixel_height,f_relativ_x,f_relativ_y,f_relativ_width,f_relativ_height,filename,account_name,Party
0,images/armin_laschet/2021-09-22_14-55-06_UTC_2...,Post,gs://ig-politik-posts/armin_laschet/2021-09-22...,1e19a944-ce54-4a50-af5f-1fb26ae46852,0.999463,"[618, 68, 698, 179]","[655.83215, 115.59756]","[687.78125, 116.61998]","[679.88385, 137.47713]","[651.548, 148.28584]",...,68,80,111,42.916667,7.943925,5.555556,12.967290,armin_laschet/2021-09-22_14-55-06_UTC_2.jpg,armin_laschet,CDU
1,images/armin_laschet/2021-09-22_14-55-06_UTC_2...,Post,gs://ig-politik-posts/armin_laschet/2021-09-22...,7c50af0d-d49f-4121-921b-173b16eb9a63,0.999458,"[865, 76, 941, 176]","[882.80505, 117.19016]","[918.87573, 113.6915]","[901.9659, 135.02817]","[887.5133, 148.83932]",...,76,76,100,60.069444,8.878505,5.277778,11.682243,armin_laschet/2021-09-22_14-55-06_UTC_2.jpg,armin_laschet,CDU
2,images/armin_laschet/2021-09-22_14-55-06_UTC_2...,Post,gs://ig-politik-posts/armin_laschet/2021-09-22...,f0902030-6596-4e02-a702-9ac7c47c5e16,0.999433,"[217, 96, 293, 203]","[247.93494, 139.99324]","[282.4035, 137.506]","[276.23734, 155.95622]","[253.7339, 175.65933]",...,96,76,107,15.069444,11.214953,5.277778,12.500000,armin_laschet/2021-09-22_14-55-06_UTC_2.jpg,armin_laschet,CDU
3,images/armin_laschet/2021-09-22_14-55-06_UTC_2...,Post,gs://ig-politik-posts/armin_laschet/2021-09-22...,d4d4e4e0-f05f-47f5-8dc3-754335fd3e62,0.995322,"[418, 111, 460, 165]","[427.0738, 133.0951]","[445.76318, 133.36816]","[434.90997, 144.35779]","[429.42117, 153.67068]",...,111,42,54,29.027778,12.967290,2.916667,6.308411,armin_laschet/2021-09-22_14-55-06_UTC_2.jpg,armin_laschet,CDU
4,images/armin_laschet/2021-09-22_14-55-06_UTC_2...,Post,gs://ig-politik-posts/armin_laschet/2021-09-22...,b57bfd65-c875-4f24-9273-ed43955386d2,0.995100,"[986, 65, 1075, 227]","[1001.7438, 125.714874]","[1003.1344, 126.80907]","[987.33704, 157.53435]","[1007.1196, 187.25154]",...,65,89,162,68.472222,7.593458,6.180556,18.925234,armin_laschet/2021-09-22_14-55-06_UTC_2.jpg,armin_laschet,CDU

Schiebe die Bilder in einen neuen Unterordner ( `Datenbank > Partei > Name `)

In [ ]:
import os
import shutil

accounts_dict = {
  "CDU": ["Armin Laschet"],
  "CSU": ["Markus Soeder"],
  "SPD": ["Olaf Scholz"],
  "FDP": ["Christian Lindner"],
  "GRUEN": ["Annalena Baerbock"],
}

def copy_directory(src, dst):
    if os.path.exists(dst):
        os.rename(dst, dst + '_backup')
    shutil.copytree(src, dst)

# New base directory for the structured data
new_base_dir = "database_v2"

# Iterate through parties and their members in the dictionary
for party, names in accounts_dict.items():
    for name in names:
        # Source and destination directory paths
        src_dir = os.path.join(DATABASE, name)
        dst_dir = os.path.join(new_base_dir, party, name)

        # Copy directory if it exists in the source
        if os.path.isdir(src_dir):
            copy_directory(src_dir, dst_dir)
        else:
            print(f"Directory not found: {src_dir}")

## Starte die Gesichtserkennung.
Die Datenbank wird beim ersten Mal für jede Partei generiert. Das erhöht die Geschwindigkeit.

In [ ]:
#@title Perform Face Recognition

DATABASE = "/content/database_v2"
EXPORT_FOLDER = "../data/" #@param {"type": "string"}
VERSION = 0 # @param {type:"number"}
FORCE_DETECT = False
BACKEND = "retinaface" #@param ['skip', 'opencv', 'ssd', 'dlib','mtcnn', 'retinaface', 'mediapipe', 'yolov8',' yunet']

def find_matches(image, model, metric, account_name):
    # Function to find matches for a given image using specified model and metric
    path = f'/content/Exports/{image}.jpg'
    col =  "distance" # f"{model}_{metric}"
    db_path = os.path.join(DATABASE, account_name)  # Updated db_path
    scores = DeepFace.find(img_path=path, db_path=db_path, model_name=model,
                           distance_metric=metric, detector_backend=BACKEND,
                           enforce_detection=FORCE_DETECT, silent=True)

    return scores, col


def process_scores(scores, col, image):
    # Process and return match details
    face_score, match_file, matches = np.nan, "", []
    if len(scores[0]) > 0:
          scores_df = scores[0]
          min_score = scores_df[scores_df[col] == scores_df[col].min()]
          face_score = min_score[col].iloc[0]
          match_file = min_score['identity'].iloc[0].split("/")[5]
          matches = [{"match_uuid": f'match_{uuid.uuid4()}', "face_uuid": image,
                      "match_file": row['identity'].split("/")[5],
                      "match_score": row[col], "model": model,
                      "distance_metric": metric}
                    for index, row in scores_df.iterrows()]

    return face_score, match_file, matches

# Main loop
model = "ArcFace"
metrics = ['euclidean_l2'] #'euclidean', 'cosine']

for metric in tqdm(metrics, desc='Processing Metrics'):
    faces, all_matches = [], []

    # Group by 'account_name' and iterate through each group
    for party, group in tqdm(all_faces_v2_df.groupby('Party'), desc='Processing parties'):
        for image in tqdm(group['face_uuid']):
            scores, col = find_matches(image, model, metric, party)
            face_score, match_file, matches = process_scores(scores, col, image)
            all_matches.extend(matches)
            if face_score is not np.nan:
                faces.append({"face_uuid": image, "match_file": match_file,
                              "match_score": face_score, "model": model,
                              "distance_metric": metric, "number_of_hits": len(scores[0])})

    # Creating and Saving DataFrames for each model-metric pair
    all_matches_df = pd.DataFrame.from_dict(all_matches)
    face_recognition_df = pd.DataFrame.from_dict(faces)

    all_matches_df.to_csv(f"{EXPORT_FOLDER}all_matches_{model}_{metric}_{VERSION}.csv", index=False)
    face_recognition_df.to_csv(f"{EXPORT_FOLDER}top_matches_{model}_{metric}_{VERSION}.csv", index=False)

Processing Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

Processing parties:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/1269 [00:00<?, ?it/s]

24-04-18 10:06:56 - arcface_weights.h5 will be downloaded to /root/.deepface/weights/arcface_weights.h5

Downloading...
From: https://github.com/serengil/deepface_models/releases/download/v1.0/arcface_weights.h5
To: /root/.deepface/weights/arcface_weights.h5



  0%|          | 0.00/137M [00:00<?, ?B/s]


  2%|▏         | 2.10M/137M [00:00<00:07, 19.2MB/s]


  6%|▌         | 8.39M/137M [00:00<00:02, 43.3MB/s]


 13%|█▎        | 17.3M/137M [00:00<00:02, 56.5MB/s]


 17%|█▋        | 23.1M/137M [00:00<00:02, 56.8MB/s]


 21%|██▏       | 29.4M/137M [00:00<00:01, 58.1MB/s]


 26%|██▌       | 35.7M/137M [00:00<00:01, 50.8MB/s]


 30%|███       | 41.4M/137M [00:00<00:01, 52.8MB/s]


 34%|███▍      | 47.2M/137M [00:00<00:01, 47.5MB/s]


 39%|███▉      | 53.5M/137M [00:01<00:01, 51.1MB/s]


 44%|████▎     | 59.8M/137M [00:01<00:01, 47.5MB/s]


 48%|████▊     | 65.5M/137M [00:01<00:01, 50.0MB/s]


 52%|█████▏    | 71.8M/137M [00:01<00:01, 53.1MB/s]


 57%|█████▋    | 77.6M/137M [00:01<00:01, 47.9MB/s]


 61%|██████    | 83.9M/137M [00:01<00:01, 51.3MB/s]


 66%|██████▌   | 90.2M/137M [00:01<00:00, 47.6MB/s]


 70%|███████   | 96.5M/137M [00:02<00:00, 42.1MB/s]


 75%|███████▍  | 102M/137M [00:02<00:00, 45.2MB/s]


 78%|███████▊  | 107M/137M [00:02<00:00, 41.3MB/s]


 83%|████████▎ | 113M/137M [00:02<00:00, 44.7MB/s]


 87%|████████▋ | 119M/137M [00:02<00:00, 47.2MB/s]


 91%|█████████ | 125M/137M [00:02<00:00, 45.7MB/s]


100%|██████████| 137M/137M [00:02<00:00, 48.5MB/s]

  0%|          | 0/551 [00:00<?, ?it/s]

  0%|          | 0/957 [00:00<?, ?it/s]

  0%|          | 0/542 [00:00<?, ?it/s]

  0%|          | 0/560 [00:00<?, ?it/s]